/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

'use strict';

import React, { Component } from 'react';
import {
  Button,
  Image,
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import PhotoUpload from 'react-native-photo-upload';
import * as AddCalendarEvent from 'react-native-add-calendar-event';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

let chrono = require('chrono-node');
let moment = require('moment-timezone');

//const msg = 'Want to get your\nhands on 40,000\ndifferent applications?\nBuilding the platforms of tomorrow\nis our purpose. Come find yours.\nTech Talk\nIntelligent Big Data for Wall StreetEs\nDr. James Zhang, a senior research engineer from the message\nScraping team will speak on the advanced research arm of\nBloomberg, using NLP and Machine Leaming to add value to the\nhuge streams of real-time data being generated by the globale\nfinancial markets. This talk concentrates on the tools and end\nproducts that Bloomberg developed for analyzing and making\npredictions from millions of news stories, social media messages\nand transaction messages each day. The impact of the data on\nthe market will also be discussed.\nBloomberg\nDate: Saturday, January 20th\nTime: 3pm\nLocation: Towne 311\nRegister now.\nhttp://tinyurl.com/ybőqhi7g\nStay connected on purpose.\n';

let request_vision = (base64img) => {

  console.log('hello');

  fetch('https://vision.googleapis.com/v1/images:annotate?key=', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      "requests": [
        {
          "features": [
            {
              "type": "LABEL_DETECTION"
            },
            {
              "type": "DOCUMENT_TEXT_DETECTION"
            }
          ],
          "image": {
            "source": {
              "imageUri": "https://lh3.googleusercontent.com/8h6vsmdaW7UKux3ldld9TTIxcGyG3AbCD_bIUCiUztE3XuIgD5aBUJeb-unMC6xCc_KKb7jgMcsf0A51v4DL8gA3LRN2Dj0AIOuCVSXMAL_fhfvAoBQPmvpnYlgP1mAMPiCrGpSes92BRofWSB3tqs7DoDOqfb_vRGcm47_WtuMy14HwQvwWZi23in7t9FN6Zch_CVah3xuAef-KV0UTaA5JK56PM5G2hFNjS85eAk8OWvYcEiGA5Eh2iwXYleTWHbveQ96iWJelfdMGxC9YbsLtjgWnlus5GVQ19N3yADHCGcRkDag1Xw4k51l6KPYBjzjLJLcy66gtNtYiQezRmsCD4l-ozXRxa_19QVdyonLjcl467H42GOx_GCT9C4zzvhdDec8W7Y_Aor5-pJShj3_JTc408H0T9T4LCEXjbw0Q-8W18JfBFNi0tJLn2RoFSyT_p4mUodGhM2bUY12vfFGMbD0uQCH3hKiXxoUAsXkaWjm_mp2x6auGmRksV2dVM_12GwPUP73Pgn7P_lztG6tfdR5sa5vUDZEwZftUhy9l8-ScAb7q2mkgUoBSqLKsxMRfnXGDl7oM70p53T9-rh4H8_ZL4HwxejrvnMTi=w455-h678-no"
            }
          }
        }
      ]
    })
  }).then((response) => {
    response.json().then((res) => {
      console.log(res.responses[0]);
      let msg = res.responses[0].fullTextAnnotation.text;
      //let title = [for (word of res.responses[0].fullTextAnnotation.pages[0].blocks[0].paragraphs[0].words) 'a'([for (letter of word.symbols) letter.text].join(''))].join('');
      //let title = 'New Event';
      let title = '';
      let words = res.responses[0].fullTextAnnotation.pages[0].blocks[0].paragraphs[0].words;
      for (let i = 0; i < words.length; i++) {
        let word = words[i];
        for (let j = 0; j < word.symbols.length; i++) {
          title += word.symbols.text;
        }
      }
      console.log(title);
      add_event(msg, title);
      console.log('add');
    });
  });

}

let process_text = (message) => message.toLowerCase().replace('time:','').split('\n').join(' ').replace('  ',' ');

let parse_date = (message) => {
  let dates = chrono.parse(message);
  console.log(dates);
  let res = Math.max.apply(Math, dates.map(e => e.text.length));
  let date = dates.find(e => e.text.length === res);
  date_est = moment.tz(chrono.parseDate(date.text), 'America/New_York');
  date_utc = moment.tz(date_est, 'Europe/Dublin');
  date_str = date_utc.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]');
  console.log(date_str);
  return date_str;
}

let add_event = (message, title) => {
  let date = parse_date(process_text(message));
  console.log(date);

  const eventConfig = {
    title: title,
    startDate: date
  }

  AddCalendarEvent.presentNewCalendarEventDialog(eventConfig)
    .then(eventId => {
      if (eventId) {
        console.warn(eventId);
      } else {
        console.warn('dismissed');
      }
    })
    .catch((error: string) => {
      console.warn(error);
    });
}

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <PhotoUpload
          onPhotoSelect={img => {
            console.log(img);
            if (img) {
              request_vision(img);
            }
          }}
        >
          <Image
            style={{
              paddingVertical: 0,
              width: 800,
              height: 1000
            }}
            resizeMode='cover'
            source={{
              'uri': 'https://www.sparklabs.com/forum/styles/comboot/theme/images/default_avatar.jpg'
            }}
          />
        </PhotoUpload>
        <Button
          onPress={() => {
            console.log('upload');
            request_vision('');
          }}
          title="Upload"
        />
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
